[package]
name = "wasinodot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libwasinodot"
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.43"
thiserror = "1.0.29"
